# Generated by Django 4.2 on 2023-05-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_auto_20190305_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
